<?
$aMenuLinks = Array(
	Array(
		"Главная", 
		"/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Объявления", 
		"/obyavleniya/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"О сервисе", 
		"/o-servise/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Личный кабинет продавца", 
		"/lichnyy-kabinet-prodavtsa/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(7))" 
	),
	Array(
		"Мои объявления", 
		"/lichnyy-kabinet-prodavtsa/moi-obyavleniya/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(7))" 
	),
	Array(
		"Личный кабинет покупателя", 
		"/lichnyy-kabinet-pokupatelya/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(6))" 
	),
	Array(
		"Избранное", 
		"/lichnyy-kabinet-pokupatelya/izbrannoe/", 
		Array(), 
		Array(), 
		"CSite::InGroup(array(6))" 
	),
	Array(
		"Новости", 
		"/o-servise/novosti/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>